package com.baldede.postman.solver.score;
    dialect "java"

import org.optaplanner.core.api.score.buildin.simplelong.SimpleLongScoreHolder;

import com.baldede.postman.domain.Location;
import com.baldede.postman.domain.Domicile;
import com.baldede.postman.domain.Stop;
import com.baldede.postman.domain.TourSolution;

global SimpleLongScoreHolder scoreHolder;

// ############################################################################
// Soft constraints
// ############################################################################

rule "distanceToPreviousStandstill"
    when
        $stop : Stop(previousStandstill != null, $distanceFromPreviousStandstill : distanceFromPreviousStandstill)
    then
        scoreHolder.addConstraintMatch(kcontext, - $distanceFromPreviousStandstill);
end

rule "distanceFromLastVisitToDomicile"
    when
        $stop : Stop(previousStandstill != null)
        not Stop(previousStandstill == $stop)
        $domicile : Domicile()
    then
        scoreHolder.addConstraintMatch(kcontext, - $stop.getDistanceTo($domicile));
end